### ISSUE TITLE
v0.1.0 todo list

### ISSUE THREAD

**Issue by omar-azmi** [omar-azmi/github_aid_ts#1]
### Take care of the following tasks before hitting `v0.1.0`

- [x] add option for setting the degree of recursion depth when traversing folders
  - DONE: 2c4a8f8a5426cf8449859eef891a5e1deb22b646

- [x] add option for branch selection and recursion for REST api (this will require us to use the [tree schema](https://docs.github.com/en/rest/git/trees#get-a-tree) instead of the [repository schema](https://docs.github.com/en/rest/repos/repos#get-a-repository))
  - [x] branch selection
    - DONE: [`782f320`](https://github.com/omar-azmi/github_aid_ts/blob/782f320bb2b89b91ed2193250295469d58587402/src/lib/gh_rest_api.ts#L31-L36)
  - [x] recursion
    - DONE: 782f320bb2b89b91ed2193250295469d58587402

- [x] add feature for checking a repository's total diskspace usage
  - DONE: 6d4e24c05af6b8e6142bd75050d4e138b98743a0

- [x] add option customizing the placement of the buttons that get injected onto the github page
  - [x] add configuration ui to `option.html`
    - DONE: b0044b475219903c755bb43c3a3afadbced97ea3, f73a7c0b536fb1b0b9d6c6de5022ff8cafa9a748
  - [x] implement the button placement function based on the user's `StorageSchema.layout` value
    - DONE: 460025f614de029ed7eea2fd0517ae2298813073
  - [x] allow redundant injected buttons
    - DONE: 6d4e24c05af6b8e6142bd75050d4e138b98743a0

- [x] fix the cropping of the `option.html` page when rendered as a popup page
  - DONE: 370c62671c88320d3b851fb14a9e2a6b3efdb708, cd1fe3b283a471f1536f1756b8ca0d5030854640

- [x] folders with only one subfolder (and no files) are previewed as "folder/subfolder" in the github table-view ui.
as a result, I am unable to match the retrieved folder sizes with the associated table row, since the table row is identified by the name "folder/subfolder", where as the folder sizes has it stored as the key "folder".
  - potential fix: make table rows be identifiable by the name string before any slashes ("/")
  - DONE: 3841ab49e65980e86e07d5ce78b477d03a674f70

- [x] reject github tokens of incorrect length (anything other than `40`), and notify the user in `option.html`
  - DONE: 460025f614de029ed7eea2fd0517ae2298813073

- [x] in `option.html`, use a single save button to save everything. the button must be at the top of the page, and there must also be a reload button
  - DONE: b0044b475219903c755bb43c3a3afadbced97ea3

- [x] add `readme.md` page. and include a "how to get token" subsection in the readme page
  - DONE: e54868af1a1b5121afbe14886a438ff1b7e0dbd6

- [x] add `license.md`. what should I even set it to?
  - DONE: e54868af1a1b5121afbe14886a438ff1b7e0dbd6

- [x] publish to extension stores (chrome store, edge store, and firefox)
  - [x] test extension in chromium
  - [x] test extension in firefox:
    - ~~ISSUE~~: firefox can't do dynamic imports of `"web_accessible_resources"`. fixing this will require discovering an alternate bypass. moved to a separate issue thread: #3
    - DONE: da74b309415ee0e2f8843c4c297ac2d12c9e9319
  - [x] prepare screenshots
    - DONE: 5d58ec857037d0d8fc30d9a076ba1c782476c582
  - [x] publish to:
    - [x] chrome webstore
      - DONE: [link to extension](https://chromewebstore.google.com/detail/github-aid/abfbcnoemiciiljhpngefacedfgebdcn)
    - [x] edge webstore
      - DONE: [link to extension](https://microsoftedge.microsoft.com/addons/detail/github-aid/gmmbjkoglimgjbdembmnllcepiejlped)
    - [x] firefox webstore
      - DONE: [link to extension](https://addons.mozilla.org/firefox/addon/github-aid/)

**Comment by omar-azmi** [comment]
tasks completed in version `v0.1.2` dbbc0828193b9179b79e4f072d93481f1ce0476e
