### ISSUE TITLE
v0.2.0 todo list

### ISSUE THREAD

**Issue by omar-azmi** [omar-azmi/github_aid_ts#2]
### Take care of the following tasks before hitting `v0.2.0`

- [ ] add option to choose if one wishes to strictly adhere to REST api in incognito mode, along with no authentication key

- [ ] add feature for downloading files and folders in a single ".tar.gz" archive file
  - [ ] develop an inhouse ".tar" file encoder and decoder using [byte_codec_ts](https://github.com/omar-azmi/byte_codec_ts)
    - PARTIAL: under development starting with commit: omar-azmi/experiments_ts@a49b73cb708d4236c6175af4659c58f04e776fc0

- [ ] create a build process for generating bookmarkletes that function in the same way as the extension, with user predefined `config` and `storage` values

- [ ] come up with a better logo (how about a seppukucat with a katana and a man bun?)

- [x] design a better and more universal `SimpleStorage` class.
currently, your storage api and techniques might be a bit finicky given their blackbox-like handling of first-time assignments/empty storage entries.
a lot of the first-time values are assined by the `option.ts` script. and it shouldn't be like that since `option.ts` should ideally deal only with the ui of `option.html`.
  - [x] setup a default-value system and link it to the "reset" button in the `options.html` page.
    - DONE: fce8dc0052484b4bdf56682b8429caa3abf69db2
  - [x] make the storage system compatible with:
    - [ ] local website storage
      - this one won't work, because `window.localStorage` can only store `Record<string, string>`, whereas our schema has arrays and objects as values inside of it.
      I could encode the values as json when "setting", and parse that json back when "getting", but that's for later.
    - [x] temporary map/object storage , so that it can work across different environments, including bookmarklets
    - DONE: 68f02591b3c175fe1d32294b2f1c33caf29a46ec
